// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yura4ka/crickter/ent/comment"
	"github.com/yura4ka/crickter/ent/commentreaction"
	"github.com/yura4ka/crickter/ent/predicate"
	"github.com/yura4ka/crickter/ent/user"
)

// CommentReactionQuery is the builder for querying CommentReaction entities.
type CommentReactionQuery struct {
	config
	ctx         *QueryContext
	order       []commentreaction.OrderOption
	inters      []Interceptor
	predicates  []predicate.CommentReaction
	withComment *CommentQuery
	withUser    *UserQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CommentReactionQuery builder.
func (crq *CommentReactionQuery) Where(ps ...predicate.CommentReaction) *CommentReactionQuery {
	crq.predicates = append(crq.predicates, ps...)
	return crq
}

// Limit the number of records to be returned by this query.
func (crq *CommentReactionQuery) Limit(limit int) *CommentReactionQuery {
	crq.ctx.Limit = &limit
	return crq
}

// Offset to start from.
func (crq *CommentReactionQuery) Offset(offset int) *CommentReactionQuery {
	crq.ctx.Offset = &offset
	return crq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (crq *CommentReactionQuery) Unique(unique bool) *CommentReactionQuery {
	crq.ctx.Unique = &unique
	return crq
}

// Order specifies how the records should be ordered.
func (crq *CommentReactionQuery) Order(o ...commentreaction.OrderOption) *CommentReactionQuery {
	crq.order = append(crq.order, o...)
	return crq
}

// QueryComment chains the current query on the "comment" edge.
func (crq *CommentReactionQuery) QueryComment() *CommentQuery {
	query := (&CommentClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commentreaction.Table, commentreaction.FieldID, selector),
			sqlgraph.To(comment.Table, comment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commentreaction.CommentTable, commentreaction.CommentColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (crq *CommentReactionQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commentreaction.Table, commentreaction.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commentreaction.UserTable, commentreaction.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CommentReaction entity from the query.
// Returns a *NotFoundError when no CommentReaction was found.
func (crq *CommentReactionQuery) First(ctx context.Context) (*CommentReaction, error) {
	nodes, err := crq.Limit(1).All(setContextOp(ctx, crq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{commentreaction.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (crq *CommentReactionQuery) FirstX(ctx context.Context) *CommentReaction {
	node, err := crq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CommentReaction ID from the query.
// Returns a *NotFoundError when no CommentReaction ID was found.
func (crq *CommentReactionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = crq.Limit(1).IDs(setContextOp(ctx, crq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{commentreaction.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (crq *CommentReactionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := crq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CommentReaction entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CommentReaction entity is found.
// Returns a *NotFoundError when no CommentReaction entities are found.
func (crq *CommentReactionQuery) Only(ctx context.Context) (*CommentReaction, error) {
	nodes, err := crq.Limit(2).All(setContextOp(ctx, crq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{commentreaction.Label}
	default:
		return nil, &NotSingularError{commentreaction.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (crq *CommentReactionQuery) OnlyX(ctx context.Context) *CommentReaction {
	node, err := crq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CommentReaction ID in the query.
// Returns a *NotSingularError when more than one CommentReaction ID is found.
// Returns a *NotFoundError when no entities are found.
func (crq *CommentReactionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = crq.Limit(2).IDs(setContextOp(ctx, crq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{commentreaction.Label}
	default:
		err = &NotSingularError{commentreaction.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (crq *CommentReactionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := crq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CommentReactions.
func (crq *CommentReactionQuery) All(ctx context.Context) ([]*CommentReaction, error) {
	ctx = setContextOp(ctx, crq.ctx, "All")
	if err := crq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CommentReaction, *CommentReactionQuery]()
	return withInterceptors[[]*CommentReaction](ctx, crq, qr, crq.inters)
}

// AllX is like All, but panics if an error occurs.
func (crq *CommentReactionQuery) AllX(ctx context.Context) []*CommentReaction {
	nodes, err := crq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CommentReaction IDs.
func (crq *CommentReactionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if crq.ctx.Unique == nil && crq.path != nil {
		crq.Unique(true)
	}
	ctx = setContextOp(ctx, crq.ctx, "IDs")
	if err = crq.Select(commentreaction.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (crq *CommentReactionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := crq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (crq *CommentReactionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, crq.ctx, "Count")
	if err := crq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, crq, querierCount[*CommentReactionQuery](), crq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (crq *CommentReactionQuery) CountX(ctx context.Context) int {
	count, err := crq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (crq *CommentReactionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, crq.ctx, "Exist")
	switch _, err := crq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (crq *CommentReactionQuery) ExistX(ctx context.Context) bool {
	exist, err := crq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CommentReactionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (crq *CommentReactionQuery) Clone() *CommentReactionQuery {
	if crq == nil {
		return nil
	}
	return &CommentReactionQuery{
		config:      crq.config,
		ctx:         crq.ctx.Clone(),
		order:       append([]commentreaction.OrderOption{}, crq.order...),
		inters:      append([]Interceptor{}, crq.inters...),
		predicates:  append([]predicate.CommentReaction{}, crq.predicates...),
		withComment: crq.withComment.Clone(),
		withUser:    crq.withUser.Clone(),
		// clone intermediate query.
		sql:  crq.sql.Clone(),
		path: crq.path,
	}
}

// WithComment tells the query-builder to eager-load the nodes that are connected to
// the "comment" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CommentReactionQuery) WithComment(opts ...func(*CommentQuery)) *CommentReactionQuery {
	query := (&CommentClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withComment = query
	return crq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CommentReactionQuery) WithUser(opts ...func(*UserQuery)) *CommentReactionQuery {
	query := (&UserClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withUser = query
	return crq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Liked bool `json:"liked,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CommentReaction.Query().
//		GroupBy(commentreaction.FieldLiked).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (crq *CommentReactionQuery) GroupBy(field string, fields ...string) *CommentReactionGroupBy {
	crq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CommentReactionGroupBy{build: crq}
	grbuild.flds = &crq.ctx.Fields
	grbuild.label = commentreaction.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Liked bool `json:"liked,omitempty"`
//	}
//
//	client.CommentReaction.Query().
//		Select(commentreaction.FieldLiked).
//		Scan(ctx, &v)
func (crq *CommentReactionQuery) Select(fields ...string) *CommentReactionSelect {
	crq.ctx.Fields = append(crq.ctx.Fields, fields...)
	sbuild := &CommentReactionSelect{CommentReactionQuery: crq}
	sbuild.label = commentreaction.Label
	sbuild.flds, sbuild.scan = &crq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CommentReactionSelect configured with the given aggregations.
func (crq *CommentReactionQuery) Aggregate(fns ...AggregateFunc) *CommentReactionSelect {
	return crq.Select().Aggregate(fns...)
}

func (crq *CommentReactionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range crq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, crq); err != nil {
				return err
			}
		}
	}
	for _, f := range crq.ctx.Fields {
		if !commentreaction.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if crq.path != nil {
		prev, err := crq.path(ctx)
		if err != nil {
			return err
		}
		crq.sql = prev
	}
	return nil
}

func (crq *CommentReactionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CommentReaction, error) {
	var (
		nodes       = []*CommentReaction{}
		withFKs     = crq.withFKs
		_spec       = crq.querySpec()
		loadedTypes = [2]bool{
			crq.withComment != nil,
			crq.withUser != nil,
		}
	)
	if crq.withComment != nil || crq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, commentreaction.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CommentReaction).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CommentReaction{config: crq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, crq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := crq.withComment; query != nil {
		if err := crq.loadComment(ctx, query, nodes, nil,
			func(n *CommentReaction, e *Comment) { n.Edges.Comment = e }); err != nil {
			return nil, err
		}
	}
	if query := crq.withUser; query != nil {
		if err := crq.loadUser(ctx, query, nodes, nil,
			func(n *CommentReaction, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (crq *CommentReactionQuery) loadComment(ctx context.Context, query *CommentQuery, nodes []*CommentReaction, init func(*CommentReaction), assign func(*CommentReaction, *Comment)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CommentReaction)
	for i := range nodes {
		if nodes[i].comment_reactions == nil {
			continue
		}
		fk := *nodes[i].comment_reactions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(comment.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "comment_reactions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (crq *CommentReactionQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*CommentReaction, init func(*CommentReaction), assign func(*CommentReaction, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CommentReaction)
	for i := range nodes {
		if nodes[i].user_comment_reactions == nil {
			continue
		}
		fk := *nodes[i].user_comment_reactions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_comment_reactions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (crq *CommentReactionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := crq.querySpec()
	_spec.Node.Columns = crq.ctx.Fields
	if len(crq.ctx.Fields) > 0 {
		_spec.Unique = crq.ctx.Unique != nil && *crq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, crq.driver, _spec)
}

func (crq *CommentReactionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(commentreaction.Table, commentreaction.Columns, sqlgraph.NewFieldSpec(commentreaction.FieldID, field.TypeUUID))
	_spec.From = crq.sql
	if unique := crq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if crq.path != nil {
		_spec.Unique = true
	}
	if fields := crq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commentreaction.FieldID)
		for i := range fields {
			if fields[i] != commentreaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := crq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := crq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := crq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := crq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (crq *CommentReactionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(crq.driver.Dialect())
	t1 := builder.Table(commentreaction.Table)
	columns := crq.ctx.Fields
	if len(columns) == 0 {
		columns = commentreaction.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if crq.sql != nil {
		selector = crq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if crq.ctx.Unique != nil && *crq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range crq.predicates {
		p(selector)
	}
	for _, p := range crq.order {
		p(selector)
	}
	if offset := crq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := crq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CommentReactionGroupBy is the group-by builder for CommentReaction entities.
type CommentReactionGroupBy struct {
	selector
	build *CommentReactionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (crgb *CommentReactionGroupBy) Aggregate(fns ...AggregateFunc) *CommentReactionGroupBy {
	crgb.fns = append(crgb.fns, fns...)
	return crgb
}

// Scan applies the selector query and scans the result into the given value.
func (crgb *CommentReactionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crgb.build.ctx, "GroupBy")
	if err := crgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommentReactionQuery, *CommentReactionGroupBy](ctx, crgb.build, crgb, crgb.build.inters, v)
}

func (crgb *CommentReactionGroupBy) sqlScan(ctx context.Context, root *CommentReactionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(crgb.fns))
	for _, fn := range crgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*crgb.flds)+len(crgb.fns))
		for _, f := range *crgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*crgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CommentReactionSelect is the builder for selecting fields of CommentReaction entities.
type CommentReactionSelect struct {
	*CommentReactionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (crs *CommentReactionSelect) Aggregate(fns ...AggregateFunc) *CommentReactionSelect {
	crs.fns = append(crs.fns, fns...)
	return crs
}

// Scan applies the selector query and scans the result into the given value.
func (crs *CommentReactionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crs.ctx, "Select")
	if err := crs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommentReactionQuery, *CommentReactionSelect](ctx, crs.CommentReactionQuery, crs, crs.inters, v)
}

func (crs *CommentReactionSelect) sqlScan(ctx context.Context, root *CommentReactionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(crs.fns))
	for _, fn := range crs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*crs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
