// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yura4ka/crickter/ent/post"
	"github.com/yura4ka/crickter/ent/postreaction"
	"github.com/yura4ka/crickter/ent/user"
)

// PostReaction is the model entity for the PostReaction schema.
type PostReaction struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Liked holds the value of the "liked" field.
	Liked bool `json:"liked,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostReactionQuery when eager-loading is set.
	Edges               PostReactionEdges `json:"edges"`
	post_reactions      *uuid.UUID
	user_post_reactions *uuid.UUID
	selectValues        sql.SelectValues
}

// PostReactionEdges holds the relations/edges for other nodes in the graph.
type PostReactionEdges struct {
	// Post holds the value of the post edge.
	Post *Post `json:"post,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostReactionEdges) PostOrErr() (*Post, error) {
	if e.loadedTypes[0] {
		if e.Post == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: post.Label}
		}
		return e.Post, nil
	}
	return nil, &NotLoadedError{edge: "post"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostReactionEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[1] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PostReaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case postreaction.FieldLiked:
			values[i] = new(sql.NullBool)
		case postreaction.FieldID:
			values[i] = new(uuid.UUID)
		case postreaction.ForeignKeys[0]: // post_reactions
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case postreaction.ForeignKeys[1]: // user_post_reactions
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PostReaction fields.
func (pr *PostReaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case postreaction.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pr.ID = *value
			}
		case postreaction.FieldLiked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field liked", values[i])
			} else if value.Valid {
				pr.Liked = value.Bool
			}
		case postreaction.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field post_reactions", values[i])
			} else if value.Valid {
				pr.post_reactions = new(uuid.UUID)
				*pr.post_reactions = *value.S.(*uuid.UUID)
			}
		case postreaction.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_post_reactions", values[i])
			} else if value.Valid {
				pr.user_post_reactions = new(uuid.UUID)
				*pr.user_post_reactions = *value.S.(*uuid.UUID)
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PostReaction.
// This includes values selected through modifiers, order, etc.
func (pr *PostReaction) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the PostReaction entity.
func (pr *PostReaction) QueryPost() *PostQuery {
	return NewPostReactionClient(pr.config).QueryPost(pr)
}

// QueryUser queries the "user" edge of the PostReaction entity.
func (pr *PostReaction) QueryUser() *UserQuery {
	return NewPostReactionClient(pr.config).QueryUser(pr)
}

// Update returns a builder for updating this PostReaction.
// Note that you need to call PostReaction.Unwrap() before calling this method if this PostReaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *PostReaction) Update() *PostReactionUpdateOne {
	return NewPostReactionClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the PostReaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *PostReaction) Unwrap() *PostReaction {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: PostReaction is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *PostReaction) String() string {
	var builder strings.Builder
	builder.WriteString("PostReaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("liked=")
	builder.WriteString(fmt.Sprintf("%v", pr.Liked))
	builder.WriteByte(')')
	return builder.String()
}

// PostReactions is a parsable slice of PostReaction.
type PostReactions []*PostReaction
