// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yura4ka/crickter/ent/post"
	"github.com/yura4ka/crickter/ent/postreaction"
	"github.com/yura4ka/crickter/ent/predicate"
	"github.com/yura4ka/crickter/ent/user"
)

// PostReactionQuery is the builder for querying PostReaction entities.
type PostReactionQuery struct {
	config
	ctx        *QueryContext
	order      []postreaction.OrderOption
	inters     []Interceptor
	predicates []predicate.PostReaction
	withPost   *PostQuery
	withUser   *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PostReactionQuery builder.
func (prq *PostReactionQuery) Where(ps ...predicate.PostReaction) *PostReactionQuery {
	prq.predicates = append(prq.predicates, ps...)
	return prq
}

// Limit the number of records to be returned by this query.
func (prq *PostReactionQuery) Limit(limit int) *PostReactionQuery {
	prq.ctx.Limit = &limit
	return prq
}

// Offset to start from.
func (prq *PostReactionQuery) Offset(offset int) *PostReactionQuery {
	prq.ctx.Offset = &offset
	return prq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (prq *PostReactionQuery) Unique(unique bool) *PostReactionQuery {
	prq.ctx.Unique = &unique
	return prq
}

// Order specifies how the records should be ordered.
func (prq *PostReactionQuery) Order(o ...postreaction.OrderOption) *PostReactionQuery {
	prq.order = append(prq.order, o...)
	return prq
}

// QueryPost chains the current query on the "post" edge.
func (prq *PostReactionQuery) QueryPost() *PostQuery {
	query := (&PostClient{config: prq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := prq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := prq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(postreaction.Table, postreaction.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, postreaction.PostTable, postreaction.PostColumn),
		)
		fromU = sqlgraph.SetNeighbors(prq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (prq *PostReactionQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: prq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := prq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := prq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(postreaction.Table, postreaction.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, postreaction.UserTable, postreaction.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(prq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PostReaction entity from the query.
// Returns a *NotFoundError when no PostReaction was found.
func (prq *PostReactionQuery) First(ctx context.Context) (*PostReaction, error) {
	nodes, err := prq.Limit(1).All(setContextOp(ctx, prq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{postreaction.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (prq *PostReactionQuery) FirstX(ctx context.Context) *PostReaction {
	node, err := prq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PostReaction ID from the query.
// Returns a *NotFoundError when no PostReaction ID was found.
func (prq *PostReactionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = prq.Limit(1).IDs(setContextOp(ctx, prq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{postreaction.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (prq *PostReactionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := prq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PostReaction entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PostReaction entity is found.
// Returns a *NotFoundError when no PostReaction entities are found.
func (prq *PostReactionQuery) Only(ctx context.Context) (*PostReaction, error) {
	nodes, err := prq.Limit(2).All(setContextOp(ctx, prq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{postreaction.Label}
	default:
		return nil, &NotSingularError{postreaction.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (prq *PostReactionQuery) OnlyX(ctx context.Context) *PostReaction {
	node, err := prq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PostReaction ID in the query.
// Returns a *NotSingularError when more than one PostReaction ID is found.
// Returns a *NotFoundError when no entities are found.
func (prq *PostReactionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = prq.Limit(2).IDs(setContextOp(ctx, prq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{postreaction.Label}
	default:
		err = &NotSingularError{postreaction.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (prq *PostReactionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := prq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PostReactions.
func (prq *PostReactionQuery) All(ctx context.Context) ([]*PostReaction, error) {
	ctx = setContextOp(ctx, prq.ctx, "All")
	if err := prq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PostReaction, *PostReactionQuery]()
	return withInterceptors[[]*PostReaction](ctx, prq, qr, prq.inters)
}

// AllX is like All, but panics if an error occurs.
func (prq *PostReactionQuery) AllX(ctx context.Context) []*PostReaction {
	nodes, err := prq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PostReaction IDs.
func (prq *PostReactionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if prq.ctx.Unique == nil && prq.path != nil {
		prq.Unique(true)
	}
	ctx = setContextOp(ctx, prq.ctx, "IDs")
	if err = prq.Select(postreaction.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (prq *PostReactionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := prq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (prq *PostReactionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, prq.ctx, "Count")
	if err := prq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, prq, querierCount[*PostReactionQuery](), prq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (prq *PostReactionQuery) CountX(ctx context.Context) int {
	count, err := prq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (prq *PostReactionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, prq.ctx, "Exist")
	switch _, err := prq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (prq *PostReactionQuery) ExistX(ctx context.Context) bool {
	exist, err := prq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PostReactionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (prq *PostReactionQuery) Clone() *PostReactionQuery {
	if prq == nil {
		return nil
	}
	return &PostReactionQuery{
		config:     prq.config,
		ctx:        prq.ctx.Clone(),
		order:      append([]postreaction.OrderOption{}, prq.order...),
		inters:     append([]Interceptor{}, prq.inters...),
		predicates: append([]predicate.PostReaction{}, prq.predicates...),
		withPost:   prq.withPost.Clone(),
		withUser:   prq.withUser.Clone(),
		// clone intermediate query.
		sql:  prq.sql.Clone(),
		path: prq.path,
	}
}

// WithPost tells the query-builder to eager-load the nodes that are connected to
// the "post" edge. The optional arguments are used to configure the query builder of the edge.
func (prq *PostReactionQuery) WithPost(opts ...func(*PostQuery)) *PostReactionQuery {
	query := (&PostClient{config: prq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	prq.withPost = query
	return prq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (prq *PostReactionQuery) WithUser(opts ...func(*UserQuery)) *PostReactionQuery {
	query := (&UserClient{config: prq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	prq.withUser = query
	return prq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Liked bool `json:"liked,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PostReaction.Query().
//		GroupBy(postreaction.FieldLiked).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (prq *PostReactionQuery) GroupBy(field string, fields ...string) *PostReactionGroupBy {
	prq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PostReactionGroupBy{build: prq}
	grbuild.flds = &prq.ctx.Fields
	grbuild.label = postreaction.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Liked bool `json:"liked,omitempty"`
//	}
//
//	client.PostReaction.Query().
//		Select(postreaction.FieldLiked).
//		Scan(ctx, &v)
func (prq *PostReactionQuery) Select(fields ...string) *PostReactionSelect {
	prq.ctx.Fields = append(prq.ctx.Fields, fields...)
	sbuild := &PostReactionSelect{PostReactionQuery: prq}
	sbuild.label = postreaction.Label
	sbuild.flds, sbuild.scan = &prq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PostReactionSelect configured with the given aggregations.
func (prq *PostReactionQuery) Aggregate(fns ...AggregateFunc) *PostReactionSelect {
	return prq.Select().Aggregate(fns...)
}

func (prq *PostReactionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range prq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, prq); err != nil {
				return err
			}
		}
	}
	for _, f := range prq.ctx.Fields {
		if !postreaction.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if prq.path != nil {
		prev, err := prq.path(ctx)
		if err != nil {
			return err
		}
		prq.sql = prev
	}
	return nil
}

func (prq *PostReactionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PostReaction, error) {
	var (
		nodes       = []*PostReaction{}
		withFKs     = prq.withFKs
		_spec       = prq.querySpec()
		loadedTypes = [2]bool{
			prq.withPost != nil,
			prq.withUser != nil,
		}
	)
	if prq.withPost != nil || prq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, postreaction.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PostReaction).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PostReaction{config: prq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, prq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := prq.withPost; query != nil {
		if err := prq.loadPost(ctx, query, nodes, nil,
			func(n *PostReaction, e *Post) { n.Edges.Post = e }); err != nil {
			return nil, err
		}
	}
	if query := prq.withUser; query != nil {
		if err := prq.loadUser(ctx, query, nodes, nil,
			func(n *PostReaction, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (prq *PostReactionQuery) loadPost(ctx context.Context, query *PostQuery, nodes []*PostReaction, init func(*PostReaction), assign func(*PostReaction, *Post)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PostReaction)
	for i := range nodes {
		if nodes[i].post_reactions == nil {
			continue
		}
		fk := *nodes[i].post_reactions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(post.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "post_reactions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (prq *PostReactionQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*PostReaction, init func(*PostReaction), assign func(*PostReaction, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PostReaction)
	for i := range nodes {
		if nodes[i].user_post_reactions == nil {
			continue
		}
		fk := *nodes[i].user_post_reactions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_post_reactions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (prq *PostReactionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := prq.querySpec()
	_spec.Node.Columns = prq.ctx.Fields
	if len(prq.ctx.Fields) > 0 {
		_spec.Unique = prq.ctx.Unique != nil && *prq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, prq.driver, _spec)
}

func (prq *PostReactionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(postreaction.Table, postreaction.Columns, sqlgraph.NewFieldSpec(postreaction.FieldID, field.TypeUUID))
	_spec.From = prq.sql
	if unique := prq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if prq.path != nil {
		_spec.Unique = true
	}
	if fields := prq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postreaction.FieldID)
		for i := range fields {
			if fields[i] != postreaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := prq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := prq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := prq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := prq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (prq *PostReactionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(prq.driver.Dialect())
	t1 := builder.Table(postreaction.Table)
	columns := prq.ctx.Fields
	if len(columns) == 0 {
		columns = postreaction.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if prq.sql != nil {
		selector = prq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if prq.ctx.Unique != nil && *prq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range prq.predicates {
		p(selector)
	}
	for _, p := range prq.order {
		p(selector)
	}
	if offset := prq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := prq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PostReactionGroupBy is the group-by builder for PostReaction entities.
type PostReactionGroupBy struct {
	selector
	build *PostReactionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (prgb *PostReactionGroupBy) Aggregate(fns ...AggregateFunc) *PostReactionGroupBy {
	prgb.fns = append(prgb.fns, fns...)
	return prgb
}

// Scan applies the selector query and scans the result into the given value.
func (prgb *PostReactionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, prgb.build.ctx, "GroupBy")
	if err := prgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PostReactionQuery, *PostReactionGroupBy](ctx, prgb.build, prgb, prgb.build.inters, v)
}

func (prgb *PostReactionGroupBy) sqlScan(ctx context.Context, root *PostReactionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(prgb.fns))
	for _, fn := range prgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*prgb.flds)+len(prgb.fns))
		for _, f := range *prgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*prgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := prgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PostReactionSelect is the builder for selecting fields of PostReaction entities.
type PostReactionSelect struct {
	*PostReactionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (prs *PostReactionSelect) Aggregate(fns ...AggregateFunc) *PostReactionSelect {
	prs.fns = append(prs.fns, fns...)
	return prs
}

// Scan applies the selector query and scans the result into the given value.
func (prs *PostReactionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, prs.ctx, "Select")
	if err := prs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PostReactionQuery, *PostReactionSelect](ctx, prs.PostReactionQuery, prs, prs.inters, v)
}

func (prs *PostReactionSelect) sqlScan(ctx context.Context, root *PostReactionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(prs.fns))
	for _, fn := range prs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*prs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := prs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
