services:
  db:
    image: postgres
    restart: always
    env_file: /server/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  cassandra:
    image: cassandra
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  pgdata:
  cassandra_data:
